apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-audit-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: audit-service
spec:
  type: {{ .Values.service.auditService.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.auditService.port | default 8005 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: audit-service
