apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-websocket-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket-service
spec:
  type: {{ .Values.service.websocketService.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.websocketService.port | default 8004 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: websocket-service
