apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-alert-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: alert-service
spec:
  type: {{ .Values.service.alertService.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.alertService.port | default 8002 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: alert-service
