apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-notification-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification-service
spec:
  type: {{ .Values.service.notificationService.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.notificationService.port | default 8003 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: notification-service
