/**
 * Auth Schema Contract: Drizzle ORM Schema for Better Auth
 *
 * This file defines the Drizzle ORM schema for authentication tables
 * required by Better Auth. These tables are stored in Neon PostgreSQL
 * and managed by the Next.js frontend.
 *
 * **IMPORTANT**: This schema is for AUTH TABLES ONLY.
 * Task data is NOT stored in this database.
 */

import { pgTable, text, timestamp, boolean } from "drizzle-orm/pg-core"

// ============================================================================
// User Table
// ============================================================================

/**
 * User table - stores user profile information
 *
 * Better Auth uses this table to manage user accounts.
 * The `name` field is used to generate avatar initials (e.g., "John Doe" → "JD").
 */
export const user = pgTable("user", {
  id: text("id").primaryKey(), // UUID generated by Better Auth
  name: text("name").notNull(), // Full name (required for avatar initials)
  email: text("email").notNull().unique(), // Unique email address
  emailVerified: boolean("emailVerified").notNull().default(false), // Email verification status
  image: text("image"), // Optional profile picture URL
  createdAt: timestamp("createdAt").notNull().defaultNow(), // Account creation timestamp
  updatedAt: timestamp("updatedAt").notNull().defaultNow(), // Last profile update
})

// ============================================================================
// Session Table
// ============================================================================

/**
 * Session table - stores active user sessions
 *
 * Better Auth uses this table to manage JWT sessions.
 * Sessions are tied to users via the `userId` foreign key.
 */
export const session = pgTable("session", {
  id: text("id").primaryKey(), // Session identifier (UUID)
  expiresAt: timestamp("expiresAt").notNull(), // Session expiration timestamp
  ipAddress: text("ipAddress"), // IP address for security tracking
  userAgent: text("userAgent"), // Browser user agent string
  userId: text("userId")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }), // Foreign key to user
})

// ============================================================================
// Account Table
// ============================================================================

/**
 * Account table - stores authentication provider accounts
 *
 * Better Auth uses this table to link users to authentication providers.
 * For Phase 2, we use "credential" provider (email/password auth).
 * The `password` field stores bcrypt-hashed passwords.
 */
export const account = pgTable("account", {
  id: text("id").primaryKey(), // Account identifier (UUID)
  accountId: text("accountId").notNull(), // Provider-specific account ID
  providerId: text("providerId").notNull(), // "credential" for email/password auth
  userId: text("userId")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }), // Foreign key to user
  accessToken: text("accessToken"), // OAuth access token (unused in Phase 2)
  refreshToken: text("refreshToken"), // OAuth refresh token (unused in Phase 2)
  idToken: text("idToken"), // OpenID Connect ID token (unused in Phase 2)
  expiresAt: timestamp("expiresAt"), // Token expiration timestamp
  password: text("password"), // Bcrypt-hashed password for email/password auth
})

// ============================================================================
// Type Inference
// ============================================================================

/**
 * Infer TypeScript types from Drizzle schema
 * These types can be imported and used throughout the application.
 */

import type { InferSelectModel, InferInsertModel } from "drizzle-orm"

// Select models (reading from database)
export type User = InferSelectModel<typeof user>
export type Session = InferSelectModel<typeof session>
export type Account = InferSelectModel<typeof account>

// Insert models (writing to database)
export type NewUser = InferInsertModel<typeof user>
export type NewSession = InferInsertModel<typeof session>
export type NewAccount = InferInsertModel<typeof account>

// ============================================================================
// Schema Metadata
// ============================================================================

/**
 * Table names (for reference)
 */
export const TABLE_NAMES = {
  USER: "user",
  SESSION: "session",
  ACCOUNT: "account",
} as const

/**
 * Relationships
 */
export const RELATIONSHIPS = {
  SESSION_TO_USER: "session.userId → user.id (cascade delete)",
  ACCOUNT_TO_USER: "account.userId → user.id (cascade delete)",
} as const

// ============================================================================
// Usage Examples (for documentation)
// ============================================================================

/**
 * Example: Querying users with Drizzle
 *
 * ```typescript
 * import { db } from "@/lib/db"
 * import { user } from "@/contracts/auth-schema"
 * import { eq } from "drizzle-orm"
 *
 * async function getUserByEmail(email: string) {
 *   const users = await db
 *     .select()
 *     .from(user)
 *     .where(eq(user.email, email))
 *     .limit(1)
 *
 *   return users[0] ?? null
 * }
 * ```
 */

/**
 * Example: Creating a new user
 *
 * ```typescript
 * import { db } from "@/lib/db"
 * import { user, type NewUser } from "@/contracts/auth-schema"
 * import { v4 as uuidv4 } from "uuid"
 *
 * async function createUser(data: Omit<NewUser, "id" | "createdAt" | "updatedAt">) {
 *   const newUser: NewUser = {
 *     id: uuidv4(),
 *     ...data,
 *     emailVerified: false,
 *     createdAt: new Date(),
 *     updatedAt: new Date(),
 *   }
 *
 *   await db.insert(user).values(newUser)
 *   return newUser
 * }
 * ```
 */

/**
 * Example: Generating avatar initials from user name
 *
 * ```typescript
 * import type { User } from "@/contracts/auth-schema"
 *
 * function getUserInitials(user: User): string {
 *   const names = user.name.trim().split(/\s+/)
 *   if (names.length === 0) return "??"
 *
 *   const initials = names
 *     .map(name => name[0]?.toUpperCase() ?? "")
 *     .join("")
 *     .slice(0, 2)
 *
 *   return initials || "??"
 * }
 *
 * // Example usage:
 * // getUserInitials({ name: "John Doe", ... }) → "JD"
 * // getUserInitials({ name: "Alice", ... }) → "A"
 * // getUserInitials({ name: "Bob Smith Johnson", ... }) → "BS"
 * ```
 */

/**
 * Example: Deleting user with cascade (sessions and accounts deleted automatically)
 *
 * ```typescript
 * import { db } from "@/lib/db"
 * import { user } from "@/contracts/auth-schema"
 * import { eq } from "drizzle-orm"
 *
 * async function deleteUser(userId: string) {
 *   // All related sessions and accounts will be deleted automatically
 *   // due to onDelete: "cascade" constraint
 *   await db.delete(user).where(eq(user.id, userId))
 * }
 * ```
 */

// ============================================================================
// Migration Notes
// ============================================================================

/**
 * To generate migration from this schema:
 *
 * ```bash
 * npx drizzle-kit generate
 * ```
 *
 * To run migration:
 *
 * ```bash
 * npx drizzle-kit migrate
 * ```
 *
 * To push schema directly to database (development only):
 *
 * ```bash
 * npx drizzle-kit push
 * ```
 */

/**
 * Expected migration output:
 *
 * ```sql
 * CREATE TABLE IF NOT EXISTS "user" (
 *   "id" text PRIMARY KEY NOT NULL,
 *   "name" text NOT NULL,
 *   "email" text NOT NULL UNIQUE,
 *   "emailVerified" boolean DEFAULT false NOT NULL,
 *   "image" text,
 *   "createdAt" timestamp DEFAULT now() NOT NULL,
 *   "updatedAt" timestamp DEFAULT now() NOT NULL
 * );
 *
 * CREATE TABLE IF NOT EXISTS "session" (
 *   "id" text PRIMARY KEY NOT NULL,
 *   "expiresAt" timestamp NOT NULL,
 *   "ipAddress" text,
 *   "userAgent" text,
 *   "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE
 * );
 *
 * CREATE TABLE IF NOT EXISTS "account" (
 *   "id" text PRIMARY KEY NOT NULL,
 *   "accountId" text NOT NULL,
 *   "providerId" text NOT NULL,
 *   "userId" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
 *   "accessToken" text,
 *   "refreshToken" text,
 *   "idToken" text,
 *   "expiresAt" timestamp,
 *   "password" text
 * );
 * ```
 */
