export { Hero } from './hero'
export { Features } from './features'
export { HowItWorks } from './how-it-works'
export { CTASection } from './cta-section'
export { Footer } from './footer'
export { GeometricBackground } from './geometric-background'